### PR TITLE
pythonlibs.version: Add pip freeze

### PR DESCRIPTION
**Pull request by sjackman**
`pip freeze` records all installed packages and their versions.

### CODE REVIEW

**Comment by jts** [comment]
This is neat and good to know. I'm not sure if I should merge changes though. I'd like this repository to contain the _exact_ code that Nick and I ran to generate the results for the paper. Especially since we link here in the text.

I see the benefit of fixing these small issues though - already I had to make one change to stably link to libhdf5 for nanopolish (this does not change the behaviour of the program). Thoughts?

**Comment by sjackman** [comment]
Tag the exact version that you used for the paper. When folk (myself included) try to replicate your results, I imagine it will bring up little issues that it would be nice to merge into the GitHub repo.

**Comment by sjackman** [comment]
I think a good name for the tag is the DOI of the associated paper, `doi:10.1038/nmeth.3444`. You may want to munge the special characters `:` and `/`.

**Comment by sjackman** [comment]
Or just `paper` would be simpler.

**Pull request merged**
